before_script:
  - export TEST_URL="https://idemo.bspb.ru/"

stages:
  - test
  - reports

tests:
  stage: test
  image: mcr.microsoft.com/playwright:bionic
  script:
    - npm install # This should install playwright
    - npm run test
  artifacts:
    when: always
    paths:
      - ./junit.xml
      - ./allure-results
    expire_in: 1 week
    reports:
      junit:
        - ./junit.xml

allure_job:
  stage: reports
  image: frankescobar/allure-docker-service
  script:
    - allure generate -c ./allure-results -o ./allure-report
  artifacts:
    paths:
      - ./allure-results
      - ./allure-report
    expire_in: 1 week
  rules:
    - when: manual
